"""Fritz full pipeline driver - creates a buggy test repo, files an issue,
then drives Fritz through the contribution workflow end-to-end.

Usage: C:/Users/sandr/.local/bin/uv.exe run python scripts/fritz_pipeline_test.py
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Config
REPOS_ROOT = Path("D:/Dev/repos")
FRITZ_TEST_REPO = "fritz-pipeline-test"
FRITZ_TEST_PATH = REPOS_ROOT / FRITZ_TEST_REPO
FRITZ_WORK_PATH = REPOS_ROOT / f"{FRITZ_TEST_REPO}-work"
FRITZ_URL = "http://127.0.0.1:10996/mcp/"

BOT_NAME = "Fritz"
BOT_ISSUE_TITLE = "Fix broken greeter in pipeline test"
BOT_BRANCH = "fix/greeter"
BOT_PR_BODY = (
    "Fixes broken greeter function. Auto-generated by Fritz pipeline test.\n\n"
    "Bug: `grt` is undefined (NameError)"
)


def log(msg: str) -> None:
    ts = time.strftime("%H:%M:%S")
    print(f"[{ts}] {msg}")


def sh(cmd: str, cwd: str | None = None, timeout: int = 30) -> str:
    try:
        r = subprocess.run(
            cmd, shell=True, cwd=cwd or str(REPOS_ROOT),
            capture_output=True, text=True, timeout=timeout,
        )
        if r.returncode != 0:
            log(f"  [WARN] cmd failed: {r.stderr.strip()[:200]}")
        return r.stdout.strip()
    except subprocess.TimeoutExpired:
        log(f"  [WARN] cmd timed out: {cmd[:80]}")
        return ""


def mcp_call(tool: str, args: dict) -> dict:
    import httpx
    payload = {
        "jsonrpc": "2.0",
        "method": "tools/call",
        "params": {"name": tool, "arguments": args},
        "id": 1,
    }
    if not _mcp_session():
        return {"error": "Session init failed"}
    try:
        r = httpx.post(
            FRITZ_URL,
            json=payload,
            headers={"Content-Type": "application/json", "Accept": "application/json, text/event-stream"},
            timeout=15,
        )
        r.raise_for_status()
        for line in r.text.splitlines():
            if line.startswith("data: "):
                return json.loads(line[6:])
        return {"error": "No data in SSE response", "raw": r.text[:500]}
    except Exception as e:
        return {"error": str(e)}


_session_ok = False


def _mcp_session() -> bool:
    global _session_ok
    if _session_ok:
        return True
    import httpx
    init = {
        "jsonrpc": "2.0",
        "method": "initialize",
        "params": {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {"name": "fritz-driver", "version": "1.0"},
        },
        "id": 1,
    }
    try:
        r = httpx.post(
            FRITZ_URL,
            json=init,
            headers={"Content-Type": "application/json", "Accept": "application/json, text/event-stream"},
            timeout=10,
        )
        r.raise_for_status()
        log("  MCP session initialized")
        _session_ok = True
        return True
    except Exception as e:
        log(f"  MCP session failed: {e}")
        return False


# Step 0: Create buggy test repo
def step0_create_test_repo():
    log("=" * 60)
    log("STEP 0: Create buggy test repo")

    sh(f"rmdir /s /q {FRITZ_TEST_PATH} 2>nul")
    sh(f"rmdir /s /q {FRITZ_WORK_PATH} 2>nul")

    pkg = FRITZ_TEST_REPO.replace("-", "_")
    pkg_path = FRITZ_TEST_PATH / "src" / pkg
    os.makedirs(pkg_path, exist_ok=True)
    os.makedirs(FRITZ_TEST_PATH / "tests", exist_ok=True)

    (FRITZ_TEST_PATH / "README.md").write_text(f"# {FRITZ_TEST_REPO}\n\nTest repo for Fritz pipeline.\n")
    (FRITZ_TEST_PATH / "pyproject.toml").write_text(f"[project]\nname = \"{FRITZ_TEST_REPO}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.12\"\n")
    (FRITZ_TEST_PATH / ".gitignore").write_text("__pycache__/\n.venv/\n")
    (pkg_path / "__init__.py").write_text("")
    (pkg_path / "greeter.py").write_text('"""A greeter."""\n\n\ndef greet(name: str) -> str:\n    return f"Hello, {grt}!"\n')
    (FRITZ_TEST_PATH / "tests" / "test_greeter.py").write_text(
        f'"""Test greeter."""\nfrom {pkg}.greeter import greet\n\n\ndef test_greet():\n    assert greet("World") == "Hello, World!"\n'
    )

    sh(f"cd {FRITZ_TEST_PATH} && git init && git add -A && git commit -m 'Initial: buggy greeter'")
    sh(f"gh repo create sandraschi/{FRITZ_TEST_REPO} --public --description 'Fritz pipeline test' --push --source {FRITZ_TEST_PATH}")
    log(f"  Repo created: github.com/sandraschi/{FRITZ_TEST_REPO}")


# Step 1: File issue
def step1_file_issue():
    log("=" * 60)
    log("STEP 1: File issue")
    body = "The `greet()` function has a NameError: `grt` is undefined (should be `name`)."
    url = sh(f"gh issue create --repo sandraschi/{FRITZ_TEST_REPO} --title \"{BOT_ISSUE_TITLE}\" --body \"{body}\" --label bug")
    log(f"  Issue: {url}")
    return url


# Logging helpers (call Fritz's own memory tools)
def log_step(phase: str, note: str, lesson: str):
    log(f"  LOG {phase}: {note[:80]}")
    mcp_call("memory_project_note", {"project": FRITZ_TEST_REPO, "note": f"{phase}: {note}"})
    mcp_call("evolution_record", {"category": "contribution", "lesson": lesson})


# Step 2: Clone and branch
def step2_clone_and_branch():
    log("=" * 60)
    log("STEP 2: Clone and branch")
    sh(f"git clone https://github.com/sandraschi/{FRITZ_TEST_REPO}.git {FRITZ_WORK_PATH}")
    sh(f"cd {FRITZ_WORK_PATH} && git checkout -b {BOT_BRANCH}")
    log(f"  Branch: {BOT_BRANCH}")


# Step 3: Fix via code_generate
def step3_fix():
    log("=" * 60)
    log("STEP 3: Generate fix via Fritz's code_generate")

    pkg = FRITZ_TEST_REPO.replace("-", "_")
    result = mcp_call("code_generate", {
        "spec": f"In src/{pkg}/greeter.py, fix NameError: variable `grt` undefined, should be `name`.",
        "repo_path": str(FRITZ_WORK_PATH),
        "file_path": f"src/{pkg}/greeter.py",
        "context": "Python 3.12",
    })
    log(f"  Result: {json.dumps(result, indent=2)[:400]}")

    content = (FRITZ_WORK_PATH / "src" / pkg / "greeter.py").read_text()
    log(f"  Generated code:\n{content}")
    return "grt" not in content


# Step 4: Commit, push, PR
def step4_submit():
    log("=" * 60)
    log("STEP 4: Commit, push, PR")
    sh("git add -A", cwd=str(FRITZ_WORK_PATH))
    sh('git commit -m "fix: correct greeter NameError (grt to name)"', cwd=str(FRITZ_WORK_PATH))
    sh(f"git push -u origin {BOT_BRANCH}", cwd=str(FRITZ_WORK_PATH), timeout=20)
    pr_url = sh(
        f"gh pr create --repo sandraschi/{FRITZ_TEST_REPO} "
        f'--title "{BOT_ISSUE_TITLE}" --body "{BOT_PR_BODY}" '
        f"--head {BOT_BRANCH} --base main",
        timeout=15,
    )
    log(f"  PR: {pr_url}")
    return pr_url


# Step 5: Merge
def step5_merge():
    log("=" * 60)
    log("STEP 5: Merge PR")
    result = sh(f"gh pr merge 1 --repo sandraschi/{FRITZ_TEST_REPO} --squash --delete-branch", timeout=15)
    log(f"  Merge: {result[:200]}")
    state = sh(f"gh pr view 1 --repo sandraschi/{FRITZ_TEST_REPO} --json state,mergedAt")
    log(f"  State: {state[:200]}")
    return "MERGED" in state


def main():
    log(f"{BOT_NAME} pipeline test starting on {FRITZ_TEST_REPO}")
    log("")

    step0_create_test_repo()
    issue_url = step1_file_issue()
    log_step("Study", f"Issue filed: {issue_url}", f"Study: {FRITZ_TEST_REPO} issue #1 needs fix")

    step2_clone_and_branch()
    ok = step3_fix()
    if not ok:
        log("[FAIL] Fix still contains grt")
        return False
    log_step("Implement", "Fixed greeter.py", f"Fixed greeter.py in {FRITZ_TEST_REPO}")

    pr_url = step4_submit()
    log_step("Submit", f"PR: {pr_url}", f"PR submitted for {FRITZ_TEST_REPO}")

    merged = step5_merge()
    log_step("Done", f"Merged: {merged}", f"Pipeline completed for {FRITZ_TEST_REPO}")

    log("=" * 60)
    log("PIPELINE COMPLETE")
    log(f"  Repo: https://github.com/sandraschi/{FRITZ_TEST_REPO}")
    log(f"  PR: {pr_url}")
    log("  Status: All tools called, fix generated, PR merged")
    log("")
    log("Tools exercised in this run:")
    log("  1. gh issue create - filed the bug report")
    log("  2. code_generate - Fritz LLM wrote the fix")
    log("  3. github_create_branch (manual) - created feature branch")
    log("  4. github_commit (manual) - staged and committed")
    log("  5. github_push (manual) - pushed to remote")
    log("  6. github_create_pr (manual via gh) - created PR")
    log("  7. github_merge_pr (manual via gh) - merged PR")
    log("  8. memory_project_note - Fritz logged each phase")
    log("  9. evolution_record - Fritz recorded lessons")
    log("")

    return True


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
