"""Fritz full pipeline driver — creates a buggy test repo, files an issue,
then drives Fritz through the contribution workflow end-to-end.

Usage: C:\Users\sandr\.local\bin\uv.exe run python scripts/fritz_pipeline_test.py
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────
REPOS_ROOT = Path("D:/Dev/repos")
FRITZ_TEST_REPO = "fritz-pipeline-test"
FRITZ_TEST_PATH = REPOS_ROOT / FRITZ_TEST_REPO
FRITZ_WORK_PATH = REPOS_ROOT / f"{FRITZ_TEST_REPO}-work"
FRITZ_URL = "http://127.0.0.1:10996/mcp/"

BOT_NAME = "Fritz"
BOT_ISSUE_TITLE = "Fix broken greeter in pipeline test"
BOT_BRANCH = "fix/greeter"
BOT_PR_BODY = (
    "Fixes broken greeter function. Auto-generated by Fritz pipeline test.\n\n"
    "Bug: `grt` is undefined (NameError)"

)


def log(msg: str) -> None:
    ts = time.strftime("%H:%M:%S")
    print(f"[{ts}] {msg}")


def sh(cmd: str, cwd: str | None = None, timeout: int = 30) -> str:
    """Run a shell command and return stdout."""
    try:
        r = subprocess.run(
            cmd, shell=True, cwd=cwd or str(REPOS_ROOT),
            capture_output=True, text=True, timeout=timeout,
        )
        if r.returncode != 0:
            log(f"  ⚠ cmd failed: {r.stderr.strip()[:200]}")
        return r.stdout.strip()
    except subprocess.TimeoutExpired:
        log(f"  ⚠ cmd timed out: {cmd[:80]}")
        return ""


def mcp_call(tool: str, args: dict) -> dict:
    """Call an MCP tool on Fritz via HTTP."""
    import httpx
    payload = {
        "jsonrpc": "2.0",
        "method": "tools/call",
        "params": {"name": tool, "arguments": args},
        "id": 1,
    }
    # Streamable HTTP: first initialize, then call
    sess = _mcp_session()
    if sess is None:
        return {"error": "Session init failed"}
    try:
        r = httpx.post(
            FRITZ_URL,
            json=payload,
            headers={"Content-Type": "application/json", "Accept": "application/json, text/event-stream"},
            timeout=15,
        )
        r.raise_for_status()
        # Parse SSE response
        text = r.text
        for line in text.splitlines():
            if line.startswith("data: "):
                return json.loads(line[6:])
        return {"error": "No data in SSE response", "raw": text[:500]}
    except Exception as e:
        return {"error": str(e)}


_session_token: str | None = None


def _mcp_session() -> bool:
    """Initialize MCP session if needed."""
    global _session_token
    import httpx
    init = {
        "jsonrpc": "2.0",
        "method": "initialize",
        "params": {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {"name": "fritz-driver", "version": "1.0"},
        },
        "id": 1,
    }
    try:
        r = httpx.post(
            FRITZ_URL,
            json=init,
            headers={"Content-Type": "application/json", "Accept": "application/json, text/event-stream"},
            timeout=10,
        )
        r.raise_for_status()
        log(f"  MCP session initialized (HTTP {r.status_code})")
        return True
    except Exception as e:
        log(f"  MCP session init failed: {e}")
        return False


# ── Step 0: Create test repo ──────────────────────────────────────────────

def step0_create_test_repo():
    log("=" * 60)
    log("STEP 0: Create buggy test repo")

    # Remove if exists
    sh(f"rmdir /s /q {FRITZ_TEST_PATH} 2>nul")
    sh(f"rmdir /s /q {FRITZ_WORK_PATH} 2>nul")

    os.makedirs(FRITZ_TEST_PATH / "src" / FRITZ_TEST_REPO, exist_ok=True)
    os.makedirs(FRITZ_TEST_PATH / "tests", exist_ok=True)

    # README
    (FRITZ_TEST_PATH / "README.md").write_text(f"# {FRITZ_TEST_REPO}\n\nA test repo for Fritz pipeline demo.\n")
    (FRITZ_TEST_PATH / "pyproject.toml").write_text(f"[project]\nname = \"{FRITZ_TEST_REPO}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.12\"\n")
    (FRITZ_TEST_PATH / ".gitignore").write_text("__pycache__/\n.venv/\n")
    (FRITZ_TEST_PATH / "src" / FRITZ_TEST_REPO / "__init__.py").write_text("")

    # Buggy greeter
    (FRITZ_TEST_PATH / "src" / FRITZ_TEST_REPO / "greeter.py").write_text(
        '"""A greeter."""\n\n\ndef greet(name: str) -> str:\n    return f"Hello, {grt}!"\n'
    )

    # Tests
    (FRITZ_TEST_PATH / "tests" / "test_greeter.py").write_text(
        '"""Test greeter."""\nfrom {PACKAGE}.greeter import greet\n\n\ndef test_greet():\n    assert greet("World") == "Hello, World!"\n'.format(PACKAGE=FRITZ_TEST_REPO.replace("-", "_"))
    )

    # Git init and push
    sh(f"cd {FRITZ_TEST_PATH} && git init && git add -A && git commit -m 'Initial: buggy greeter'")
    sh(f"gh repo create sandraschi/{FRITZ_TEST_REPO} --public --description 'Fritz pipeline test' --push --source {FRITZ_TEST_PATH} --remote origin")

    log(f"  Created repo: github.com/sandraschi/{FRITZ_TEST_REPO}")
    return True


# ── Step 1: File issue ────────────────────────────────────────────────────

def step1_file_issue():
    log("=" * 60)
    log("STEP 1: File issue")

    body = "The `greet()` function has a NameError: `grt` is undefined (should be `name`)."
    result = sh(f"gh issue create --repo sandraschi/{FRITZ_TEST_REPO} --title \"{BOT_ISSUE_TITLE}\" --body \"{body}\" --label bug")
    log(f"  Issue filed: {result}")
    return "1" if "issues" in result else None


# ── Step 2: Clone + branch ────────────────────────────────────────────────

def step2_create_branch():
    log("=" * 60)
    log("STEP 2: Clone and branch")

    sh(f"git clone https://github.com/sandraschi/{FRITZ_TEST_REPO}.git {FRITZ_WORK_PATH}")
    sh(f"cd {FRITZ_WORK_PATH} && git checkout -b {BOT_BRANCH}")
    log(f"  Branch {BOT_BRANCH} created")
    return True


# ── Step 3: Fix via codegen ───────────────────────────────────────────────

def step3_fix_with_codegen():
    log("=" * 60)
    log("STEP 3: Generate fix via code_generate")

    spec = (
        f"In src/{FRITZ_TEST_REPO}/greeter.py, fix the NameError: "
        f"variable `grt` is undefined, should be `name`."
    )
    result = mcp_call("code_generate", {
        "spec": spec,
        "repo_path": str(FRITZ_WORK_PATH),
        "file_path": f"src/{FRITZ_TEST_REPO}/greeter.py",
        "context": "Python 3.12, single function greet(name: str) -> str",
    })
    log(f"  code_generate: {json.dumps(result, indent=2)[:500]}")

    # Read back the file to confirm fix
    content = (FRITZ_WORK_PATH / "src" / FRITZ_TEST_REPO / "greeter.py").read_text()
    log(f"  Fixed file:\n{content}")
    return "grt" not in content


# ── Step 4: Log documentation ─────────────────────────────────────────────

def log_study(issue_url: str):
    log("=" * 60)
    log("LOG: Study phase")
    result = mcp_call("memory_project_note", {
        "project": FRITZ_TEST_REPO,
        "note": f"Study: Issue {issue_url} — greeter.py has NameError. Need to fix grt→name.",
    })
    log(f"  memory_project_note: {result.get('success', str(result)[:100])}")
    result = mcp_call("evolution_record", {
        "category": "contribution",
        "lesson": f"Study completed for {FRITZ_TEST_REPO} issue 1",
    })
    log(f"  evolution_record: {result.get('success', str(result)[:100])}")


def log_implement():
    log("=" * 60)
    log("LOG: Implementation phase")
    result = mcp_call("memory_project_note", {
        "project": FRITZ_TEST_REPO,
        "note": "Implement: Fixed greeter.py — replaced undefined variable grt with name parameter.",
    })
    log(f"  memory_project_note: {result.get('success', str(result)[:100])}")
    result = mcp_call("evolution_record", {
        "category": "contribution",
        "lesson": f"Fixed greeter.py in {FRITZ_TEST_REPO} — one line change, grt→name",
    })
    log(f"  evolution_record: {result.get('success', str(result)[:100])}")


def log_submit(pr_url: str):
    log("=" * 60)
    log("LOG: Submit phase")
    result = mcp_call("memory_project_note", {
        "project": FRITZ_TEST_REPO,
        "note": f"PR created: {pr_url}",
    })
    log(f"  memory_project_note: {result.get('success', str(result)[:100])}")
    result = mcp_call("evolution_record", {
        "category": "contribution",
        "lesson": f"PR submitted for {FRITZ_TEST_REPO}: {pr_url}",
    })
    log(f"  evolution_record: {result.get('success', str(result)[:100])}")


def log_done():
    log("=" * 60)
    log("LOG: Done phase")
    result = mcp_call("evolution_record", {
        "category": "contribution",
        "lesson": f"Full contribution pipeline completed for {FRITZ_TEST_REPO}: issue→branch→fix→PR→merge",
    })
    log(f"  evolution_record: {result.get('success', str(result)[:100])}")
    result = mcp_call("memory_project_note", {
        "project": FRITZ_TEST_REPO,
        "note": f"Done: Full pipeline completed. Issue filed, fix generated, PR merged.",
    })
    log(f"  memory_project_note: {result.get('success', str(result)[:100])}")


# ── Step 5: Commit + push + PR ────────────────────────────────────────────

def step5_submit():
    log("=" * 60)
    log("STEP 5: Commit, push, PR")

    sh("git add -A", cwd=str(FRITZ_WORK_PATH))
    sh(f'git commit -m "fix: correct greeter NameError (grt → name)"', cwd=str(FRITZ_WORK_PATH))
    sh(f"git push -u origin {BOT_BRANCH}", cwd=str(FRITZ_WORK_PATH), timeout=20)

    # PR via gh CLI
    pr_url = sh(
        f"gh pr create --repo sandraschi/{FRITZ_TEST_REPO} "
        f'--title "{BOT_ISSUE_TITLE}" '
        f'--body "{BOT_PR_BODY}" '
        f"--head {BOT_BRANCH} --base main",
        timeout=15,
    )
    log(f"  PR: {pr_url}")
    return pr_url


# ── Step 6: Merge PR ──────────────────────────────────────────────────────

def step6_merge_pr():
    log("=" * 60)
    log("STEP 6: Merge PR")

    result = sh(f"gh pr merge 1 --repo sandraschi/{FRITZ_TEST_REPO} --squash --delete-branch", timeout=15)
    log(f"  Merge result: {result[:200] if result else 'OK'}")

    # Verify
    state = sh(f"gh pr view 1 --repo sandraschi/{FRITZ_TEST_REPO} --json state,mergedAt")
    log(f"  PR state: {state[:200]}")
    return "MERGED" in state


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    log(f"{BOT_NAME} pipeline test starting")
    log(f"  Repo: {FRITZ_TEST_REPO}")
    log("")

    step0_create_test_repo()
    issue_id = step1_file_issue()
    log_study(f"https://github.com/sandraschi/{FRITZ_TEST_REPO}/issues/1")
    step2_create_branch()
    ok = step3_fix_with_codegen()
    if not ok:
        log("  ✗ Fix verification failed!")
        return False
    log_implement()
    pr_url = step5_submit()
    log_submit(pr_url)
    merged = step6_merge_pr()
    log_done()

    log("=" * 60)
    log("PIPELINE COMPLETE")
    log(f"  Repo: https://github.com/sandraschi/{FRITZ_TEST_REPO}")
    log(f"  PR: {pr_url}")
    log(f"  Merged: {merged}")
    log("")

    return True


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
